from bacterial_taxonomy import Phylum, Domain, Classs, Order, Family, Genus, Species


class Bacterial_phyla(Phylum, Domain):
    def __init__(self, data):
        self.data = data(dict())

    def data(self, clasification):
        self.clasification = clasification

    def clasification(): [
        {
            Domain: "Bacteria",
            Phylum: "Acidobacteriota",
            Classs: "",
            "Clade": "",
            "Group": "Gram-negative",
        },
        {
            Domain: "Bacteria",
            Phylum: "Actinomycetota",
            Classs: "",
            "Clade": "Terrabacteria",
            "Group": "Gram-positive"
        },
        {
            Domain: "Bacteria",
            Phylum: "Aquificota",
            Classs: "",
            "Clade": "",
            "Group": "Gram-negative",
        },
        {
            Domain: "Bacteria",
            Phylum: "Armatimonadota",
            Classs: "",
            "Clade": "Terrabacteria",
            "Group": "Gram-negative",
        },
        {
            Domain: "Bacteria",
            Phylum: "Armatimonadota",
            Classs: "",
            "Clade": "Terrabacteria",
            "Group": "Gram-negative"
        },
        {
            Domain: "Bacteria",
            Phylum: "Armatimonadota",
            Classs: "",
            "Clade": "Terrabacteria",
            "Group": "Gram-negative",
        },
        {
            Domain: "Bacteria",
            Phylum: "Atribacterota",
            Classs: "",
            "Clade": "Terrabacteria",
            "Group": "",
        },
        {
            Domain: "Bacteria",
            Phylum: "Bacillota",
            Classs: "",
            "Clade": "Terrabacteria",
            "Group": "Gram-positive",
        },
        {
            Domain: "Bacteria",
            Phylum: "Bacteroidota",
            Classs: "",
            "Clade": "Terrabacteria",
            "Group": "Gram-negative",
        },
        {
            Domain: "Bacteria",
            Phylum: "Balneolota",
            Classs: "",
            "Clade": "",
            "Group": "",
        },
        {
            Domain: "Bacteria",
            Phylum: "Bdellovibrionota",
            Classs: "",
            "Clade": "",
            "Group": "",
        },
        {
            Domain: "Bacteria",
            Phylum: "Caldisericum",
            Classs: "",
            "Clade": "Caldisericia",
            "Group": "",
        },
        {
            Domain: "Bacteria",
            Phylum: "Caldithrix",
            Classs: "",
            "Clade": "",
            "Group": "",
        },
        {   Domain: "Bacteria",
            Phylum: "Campylobacterota",
            Classs: "",
            "Clade": "",
            "Group": "Gram-negative",
        },
        {   Domain: "Bacteria",
            Phylum: "Chlamydiota",
            Classs: "Chlamydiia",
            Order: "Chlorobiales",
            "Clade": "",
            "Group": "Gram-negative",
        },
        {   Domain: "Bacteria",
            Phylum: "Chlorobiota",
            Classs: "Chlorobia",
            Order: "Chlorobiales",
            "Clade": "",
            "Group": "Gram-negative",
        },
        {   Domain: "Bacteria",
            Phylum: "Chloroflexota",
            Classs: "Chloroflexia, Dehalococcoidia, Thermomicrobiia",
            Order: "Chlorobiales",
            "Clade": "Terrabacteria",
            "Group": "Gram-negative, Gram-positive, diderms",
        },
        {   Domain: "Bacteria",
            Phylum: "Chrysiogenota",
            Classs: "Chrysiogenetes",
            Order: "Chrysiogenales",
            Family: "Chrysiogonaceae",
            "Clade": "",
            "Group": "Gram-negative",
        },
        {   Domain: "Bacteria",
            Phylum: "Coprothermobacterota",
            Classs: "",
            Order: "",
            Family: "",
            "Clade": "",
            "Group": "",
        },
        {   Domain: "Bacteria",
            Phylum: "Coprothermobacterota",
            Classs: "",
            Order: "",
            Family: "",
            "Clade": "",
            "Group": "",
        },
        {   Domain: "Bacteria",
            Phylum: "Deferribacterota",
            Classs: "Deferribacteres",
            Order: "Deferribacterales",
            Family: "Deferribacteraceae",
            "Clade": "",
            "Group": "",
        },
        {   Domain: "Bacteria",
            Phylum: "Deinococcota",
            Classs: "Deinococci",
            Order: "Deinococcales, Thermales",
            Family: "Deinococcaceae, Thermaceae",
            "Clade": "",
            "Group": "Gram-negative, Gram-positive",
        },
        {   Domain: "Bacteria",
            Phylum: "Dictyoglomota",
            Classs: "Dictyoglomia",
            Order: "Dictyoglomales",
            Family: "Dictyoglomaceae",
            Genus: "Dictyoglomus",
            Species: "D. thermophilum, D. turgidum",
            "Clade": "",
            "Group": "Gram-negative, Gram-positive",
        },
        {   Domain: "Bacteria",
            Phylum: "Elusimicrobiota",
            Classs: "Elusimicrobia, Endomicrobiia",
            Order: "",
            Family: "",
            Genus: "",
            Species: "",
            "Clade": "",
            "Group": "",
        },

    ]
