import enterobacteriaceae_domain as Enterobacteriaceae

## Géneros dentro de la familia de la bacteria Enterobacteriaceae --Lista Incompleta y Preliminar--
biostraticola = Enterobacteriaceae()
buttiauxella = Enterobacteriaceae()
cedecea = Enterobacteriaceae()
citrobacter = Enterobacteriaceae()
dickeya = Enterobacteriaceae()
enterobacillus = Enterobacteriaceae()
enterobacter = Enterobacteriaceae()
escherichia = Enterobacteriaceae()
franconibacter = Enterobacteriaceae()
gibbsiella = Enterobacteriaceae()
izhakiella = Enterobacteriaceae()
klebsiella = Enterobacteriaceae()
kluyvera = Enterobacteriaceae()
kosakonia = Enterobacteriaceae()
leclernia = Enterobacteriaceae()
lelliottia = Enterobacteriaceae()
limnobaculum = Enterobacteriaceae()
mangrovibacter = Enterobacteriaceae()
metakosakonia = Enterobacteriaceae()
phytobacter = Enterobacteriaceae()
pluralibacter = Enterobacteriaceae()
pseudescherichia = Enterobacteriaceae()
pseudocitrobacter = Enterobacteriaceae()
raoultella = Enterobacteriaceae()
rosenbergiella = Enterobacteriaceae()
saccharobacter = Enterobacteriaceae()
salmonella = Enterobacteriaceae()
scandinavium = Enterobacteriaceae()
serratia = Enterobacteriaceae()
shigella = Enterobacteriaceae()
shimwellia = Enterobacteriaceae()
siccibacter = Enterobacteriaceae()
trabulsiellla = Enterobacteriaceae()
yokenella = Enterobacteriaceae()
