##Clase Enterobacteriae con sus "atributos"

class Enterobacteriaceae:
        def __init__(self, name, genus, species, strain, strain_number, taxonomy_id, taxonomy_rank, taxonomy_parent_id, taxonomy_parent_name, taxonomy_parent_rank, taxonomy_kingdom, taxonomy_phylum, taxonomy_class, taxonomy_order, taxonomy_family, taxonomy_genus, taxonomy_species, taxonomy_strain, taxonomy_strain_number, taxonomy_common_name, taxonomy_scientific_name, taxonomy_synonym, taxonomy_author, taxonomy_year, taxonomy_journal, taxonomy_volume, taxonomy_issue, taxonomy_pages, taxonomy_doi, taxonomy_pmid, taxonomy_pmcid, taxonomy_url, taxonomy_reference, taxonomy_comment, taxonomy_reference_type, taxonomy_reference_author, taxonomy_reference_year, taxonomy_reference_journal, taxonomy_reference_volume, taxonomy_reference_issue, taxonomy_reference_pages, taxonomy_reference_doi, taxonomy_reference_pmid, taxonomy_reference_pmcid):
            self.name = name
            self.genus = genus
            self.species = species
            self.strain = strain
            self.strain_number = strain_number
            self.taxonomy_id = taxonomy_id
            self.taxonomy_rank = taxonomy_rank
            self.taxonomy_parent_id = taxonomy_parent_id
            self.taxonomy_parent_name = taxonomy_parent_name
            self.taxonomy_parent_rank = taxonomy_parent_rank
            self.taxonomy_kingdom = taxonomy_kingdom
            self.taxonomy_phylum = taxonomy_phylum
            self.taxonomy_class = taxonomy_class
            self.taxonomy_order = taxonomy_order
            self.taxonomy_family = taxonomy_family
            self.taxonomy_genus = taxonomy_genus
            self.taxonomy_species = taxonomy_species
            self.taxonomy_strain = taxonomy_strain
            self.taxonomy_strain_number = taxonomy_strain_number
            self.taxonomy_common_name = taxonomy_common_name
            self.taxonomy_scientific_name = taxonomy_scientific_name
            self.taxonomy_synonym = taxonomy_synonym
            self.taxonomy_author = taxonomy_author
            self.taxonomy_year = taxonomy_year
            self.taxonomy_journal = taxonomy_journal
            self.taxonomy_volume = taxonomy_volume
            self.taxonomy_issue = taxonomy_issue
            self.taxonomy_pages = taxonomy_pages
            self.taxonomy_doi = taxonomy_doi
            self.taxonomy_pmid = taxonomy_pmid
            self.taxonomy_pmcid = taxonomy_pmcid
            self.taxonomy_url = taxonomy_url
            self.taxonomy_reference = taxonomy_reference
            self.taxonomy_comment = taxonomy_comment
            self.taxonomy_reference_type = taxonomy_reference_type
            self.taxonomy_reference_author = taxonomy_reference_author
            self.taxonomy_reference_year = taxonomy_reference_year
            self.taxonomy_reference_journal = taxonomy_reference_journal
            self.taxonomy_reference_volume = taxonomy_reference_volume
            self.taxonomy_reference_issue = taxonomy_reference_issue
            self.taxonomy_reference_pages = taxonomy_reference_pages
            self.taxonomy_reference_doi = taxonomy_reference_doi
            self.taxonomy_reference_pmid = taxonomy_reference_pmid
            self.taxonomy_reference_pmcid = taxonomy_reference_pmcid


## Géneros dentro de la familia de la bacteria Enterobacteriaceae --Lista Incompleta y Preliminar--
biostraticola = Enterobacteriaceae()
buttiauxella = Enterobacteriaceae()
cedecea = Enterobacteriaceae()
citrobacter = Enterobacteriaceae()
dickeya = Enterobacteriaceae()
enterobacillus = Enterobacteriaceae()
enterobacter = Enterobacteriaceae()
escherichia= Enterobacteriaceae()
franconibacter = Enterobacteriaceae()
gibbsiella = Enterobacteriaceae()
izhakiella = Enterobacteriaceae()
klebsiella = Enterobacteriaceae()
kluyvera = Enterobacteriaceae()
kosakonia = Enterobacteriaceae()
leclernia = Enterobacteriaceae()
lelliottia = Enterobacteriaceae()
limnobaculum = Enterobacteriaceae()
mangrovibacter = Enterobacteriaceae()
metakosakonia = Enterobacteriaceae()
phytobacter = Enterobacteriaceae()
pluralibacter = Enterobacteriaceae()
pseudescherichia = Enterobacteriaceae()
pseudocitrobacter = Enterobacteriaceae()
raoultella = Enterobacteriaceae()
rosenbergiella = Enterobacteriaceae()
saccharobacter = Enterobacteriaceae()
salmonella = Enterobacteriaceae()
scandinavium = Enterobacteriaceae()
serratia = Enterobacteriaceae()
shigella = Enterobacteriaceae()
shimwellia = Enterobacteriaceae()
siccibacter = Enterobacteriaceae()
trabulsiellla = Enterobacteriaceae()
yokenella = Enterobacteriaceae()
